### ISSUE TITLE
ValueError: Failed to parse line: u' = [\xe0 jour] develop -> origin/develop'

### ISSUE THREAD

**Issue by Marthym** [earwig/git-repo-updater#11]
Hi, it's not working for me, I have this error when I try to update all my repo.

Regards 
Frédéric

~~~
$ gitup ~/workspace/longback                                                                                                                                                                                 ⏎
gitup: the git-repo-updater

Directory "/home/lo/workspace/longback" contains 13 git repositories:
    babylon:
        Fetching originTraceback (most recent call last):
  File "/usr/local/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.2.3', 'console_scripts', 'gitup')()
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 90, in run
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 82, in main
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 296, in update_directories
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 275, in _update_directory
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 256, in _update_subdirectories
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 239, in _update_repository
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 98, in _fetch_remotes
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.1-py2.7.egg/git/remote.py", line 651, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.1-py2.7.egg/git/remote.py", line 588, in _get_fetch_info_from_stderr
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.1-py2.7.egg/git/remote.py", line 588, in <genexpr>
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.1-py2.7.egg/git/remote.py", line 241, in _from_line
    raise ValueError("Failed to parse line: %r" % line)
ValueError: Failed to parse line: u' = [\xe0 jour]          develop    -> origin/develop'
~~~

**Comment by earwig** [comment]
Looks like this is an issue with GitPython.

Strange, because I see https://github.com/gitpython-developers/GitPython/pull/68 which means it should have been fixed...

[This line](https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L552) is the current version of their fix. @Marthy,m can you tell us your OS and the output of the `locale` command?

**Comment by Marthym** [comment]
Hi, I'm on Debian 8.0
~~~
Linux 64b84b5f182b 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3 (2015-04-23) x86_64 x86_64 x86_64 GNU/Linux
~~~

``` sh
locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
```

**Comment by earwig** [comment]
Okay, I opened gitpython-developers/GitPython#290, so we'll have to wait for that to be fixed.

**Comment by earwig** [comment]
@Marthym: The issue seems to have been fixed in the current development version of GitPython. Can you verify? You'll need to clone https://github.com/gitpython-developers/GitPython and install it from source.

**Comment by earwig** [comment]
Assuming this is fixed.
