### ISSUE TITLE
Incompatibility with python3.4

### ISSUE THREAD

**Issue by teto** [earwig/git-repo-updater#17]
From git master HEAD: 
```
$gitup --add ~/myrepo
Traceback (most recent call last):
  File "/usr/local/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.3', 'console_scripts', 'gitup')()
  File "/usr/local/lib/python3.4/dist-packages/gitup-0.3-py3.4.egg/gitup/script.py", line 100, in run
  File "/usr/local/lib/python3.4/dist-packages/gitup-0.3-py3.4.egg/gitup/script.py", line 83, in main
  File "/usr/local/lib/python3.4/dist-packages/gitup-0.3-py3.4.egg/gitup/config.py", line 84, in add_bookmarks
  File "/usr/local/lib/python3.4/dist-packages/gitup-0.3-py3.4.egg/gitup/config.py", line 59, in _save_config_file
  File "/usr/lib/python3.4/configparser.py", line 897, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.4/configparser.py", line 901, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: 'str' does not support the buffer interface
```

**Comment by earwig** [comment]
Whoops, I thought I had fixed those things. Will take a look.

**Comment by teto** [comment]
I confirm the fix works thanks :)
