### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by janapejic** [earwig/git-repo-updater#24]
Traceback (most recent call last):
  File "/usr/local/Cellar/gitup/0.3/libexec/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.3', 'console_scripts', 'gitup')()
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/script.py", line 100, in run
    main()
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/script.py", line 92, in main
    update_directories(args.directories_to_update, update_args)
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/update.py", line 220, in update_directories
    _update_directory(full_path, update_args)
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/update.py", line 201, in _update_directory
    _update_subdirectories(path, update_args)
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/update.py", line 185, in _update_subdirectories
    _update_repository(repo, *update_args)
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/update.py", line 166, in _update_repository
    _fetch_remotes(remotes)
  File "/usr/local/Cellar/gitup/0.3/libexec/lib/python2.7/site-packages/gitup/update.py", line 75, in _fetch_remotes
    results = remote.fetch(progress=_ProgressMonitor())
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/remote.py", line 643, in fetch
    kwargs = add_progress(kwargs, self.repo.git, progress)
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/remote.py", line 51, in add_progress
    v = git.version_info
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/cmd.py", line 462, in version_info
    return self._version_info
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/cmd.py", line 439, in __getattr__
    return LazyMixin.__getattr__(self, name)
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/gitdb/util.py", line 237, in __getattr__
    self._set_cache_(attr)
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/cmd.py", line 445, in _set_cache_
    version_numbers = self._call_process('version').split(' ')[2]
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/cmd.py", line 834, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/local/Cellar/gitup/0.3/libexec/vendor/lib/python2.7/site-packages/git/cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [Errno 24] Too many open files

**Comment by earwig** [comment]
#9?

**Comment by janapejic** [comment]
It seems so.

**Comment by earwig** [comment]
So does that solve your problem?

**Comment by janapejic** [comment]
I just added all my repos as bookmarks and this way it does not crash any more.
