### ISSUE TITLE
Error on updating after a certain amount of repo's.

### ISSUE THREAD

**Issue by DracoMilesX** [earwig/git-repo-updater#32]
Hello I am getting the following error when I am updating after a while.

It seems to happen after a certain amount of repo's.

```
Traceback (most recent call last):
  File "/usr/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.4.dev0', 'console_scripts', 'gitup')()
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 137, in run
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 129, in main
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 245, in update_direc                                                                                                                                                             tories
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 226, in _dispatch
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 208, in _dispatch_to                                                                                                                                                             _subdirs
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 178, in _update_repo                                                                                                                                                             sitory
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 107, in _update_bran                                                                                                                                                             ch
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/refs/symb                                                                                                                                                             olic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/refs/symb                                                                                                                                                             olic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(                                                                                                                                                             self.repo, self.path)))
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/objects/b                                                                                                                                                             ase.py", line 65, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/db.py", l                                                                                                                                                             ine 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/cmd.py",                                                                                                                                                              line 992, in get_object_header
    cmd = self._get_persistent_cmd("cat_file_header", "cat_file", batch_check=Tr                                                                                                                                                             ue)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/cmd.py",                                                                                                                                                              line 975, in _get_persistent_cmd
    cmd = self._call_process(cmd_name, *args, **options)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/cmd.py",                                                                                                                                                              line 929, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.6-py2.7.egg/git/cmd.py",                                                                                                                                                              line 625, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [Errno 24] Too many open files
```

**Comment by earwig** [comment]
See #9

**Comment by DracoMilesX** [comment]
Well I added the repo's to bookmarks like some one suggested and that solved it and gave me another error:

`  File "/usr/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.4.dev0', 'console_scripts', 'gitup')()
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 137, in run
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 132, in main
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 237, in update_bookmarks
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 226, in _dispatch
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 208, in _dispatch_to_subdirs
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 178, in _update_repository
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 117, in _update_branch
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 463, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 929, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 713, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git merge-base 4f057bfe5eb15fb494b1efa8a90eb8fdb86e3976 fae9755ffb7f7cebb4518101da255202aae9cdb8' returned with exit code 1
`

For the rest smmap, gitup, gitpython are the latest versions.

**Comment by earwig** [comment]
Maybe try it now, with the original command?

**Comment by DracoMilesX** [comment]
Thank you by the looks of it it is working. Both the normal gitup /../../ and the gitup after added repo's.

The only issue I came across was with this repo: https://github.com/snipe/snipe-it but it might had been corrupted since after removing it and adding it again it walks through it. Will need to check once their are new commits it can update too.

But this is the error it had:

`  File "/usr/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.4.dev0', 'console_scripts', 'gitup')()
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 137, in run
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 129, in main
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 254, in update_direc                                                                                                                                                             tories
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 235, in _dispatch
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 211, in _dispatch_mu                                                                                                                                                             lti
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 179, in _update_repo                                                                                                                                                             sitory
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 118, in _update_bran                                                                                                                                                             ch
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py",                                                                                                                                                              line 466, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py",                                                                                                                                                              line 934, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/lib/python2.7/site-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py",                                                                                                                                                              line 718, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git merge-base 4f057bfe5eb15fb494b1efa8a90eb8fdb86e397                                                                                                                                                             6 16014945b642894240a7082e213a3055b8348ffa' returned with exit code 1
`

I guess this is solved for the original issue.

**Comment by earwig** [comment]
Yeah, that looks like it might be repo corruption. If anything, we might want to add a nicer error message. If it happens again, open another issue.
