### ISSUE TITLE
fails for repos with local ahead changes with upstream behind

### ISSUE THREAD

**Issue by childnode** [earwig/git-repo-updater#33]
:information_source:  current gitup [dev@f7a060af](https://github.com/earwig/git-repo-updater/commit/f7a060afe6bb4c77819b30d91bd857491e16ad35)

The repo:

```
 == BRANCHES == 
* master  7f6c811 [origin/master] some changes
  master2 b72feb7 [origin/master: 160 ahead, 100 behins] some playground changes

```

the error:

```
/home/marcel/Projects/repo (1 repo):
    repoName:
       Fetching origin (66/66): branch update (master).
        Updating master: done.
        Updating master2: Traceback (most recent call last):
  File "/usr/local/bin/gitup", line 11, in <module>
    load_entry_point('gitup==0.4.dev0', 'console_scripts', 'gitup')()
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 137, in run
  File "build/bdist.linux-x86_64/egg/gitup/script.py", line 129, in main
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 254, in update_directories
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 240, in _dispatch
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 179, in _update_repository
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 118, in _update_branch
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py", line 466, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py", line 934, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.0.8-py2.7.egg/git/cmd.py", line 718, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git merge-base b72feb7eefef00573061934097cd64266ad60a40 7f6c811d0f7b5896f2f49035a8190176a6cbeb01' returned with exit code 1

```

**Comment by earwig** [comment]
Super-delayed response, but I think this is fixed by a4810c3c5c4eac0a2dedf2c76777d77e5eef1cef.
