### ISSUE TITLE
error when install on windows:  "'module' object has no attribute '"

### ISSUE THREAD

**Issue by seanvree** [earwig/git-repo-updater#39]
Windows 10E
Running python 2.7 x86

Any ideas?

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd c:\



c:\>git clone git://github.com/earwig/git-repo-updater.git
Cloning into 'git-repo-updater'...
remote: Counting objects: 413, done.
Receiving objects:  87% (360/413)   0 (delta 0), pack-reused 413R
Receiving objects: 100% (413/413), 94.97 KiB | 0 bytes/s, done.
Resolving deltas: 100% (251/251), done.

c:\>cd git-repo-updater

c:\git-repo-updater>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, find_packages
  File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 23, in <module>
    __version__ = setuptools.version.__version__
AttributeError: 'module' object has no attribute '__version__'

c:\git-repo-updater>python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, find_packages
  File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 23, in <module>
    __version__ = setuptools.version.__version__
AttributeError: 'module' object has no attribute '__version__'

c:\git-repo-updater>

```

**Comment by earwig** [comment]
It sounds like your installation of setuptools is broken somehow. That's definitely unexpected and I've never seen it before. I don't think it has anything to do with my end.

Try reinstalling it as described [here](https://packaging.python.org/installing/)?

**Comment by seanvree** [comment]
@earwig - Yeah, I can't figure it out. I'll close this. 

You have any ideas how to get around using setuptools?  Really love this package man, great work. 

THX.
