### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by jeffbabuyo** [earwig/git-repo-updater#57]
Hello @earwig 

I am getting this error after installing to a new workstation.

```Traceback (most recent call last):
  File "/home/dogstring/.local/bin/gitup", line 11, in <module>
    load_entry_point('gitup==0.5.1', 'console_scripts', 'gitup')()
  File "/home/dogstring/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dogstring/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/dogstring/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/dogstring/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/gitup/cli.py", line 18, in <module>
  File "build/bdist.linux-x86_64/egg/gitup/update.py", line 15, in <module>
  File "/home/dogstring/.local/lib/python2.7/site-packages/GitPython-3.1.0-py2.7.egg/git/__init__.py", line 40, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "/home/dogstring/.local/lib/python2.7/site-packages/GitPython-3.1.0-py2.7.egg/git/config.py", line 28, in <module>
    import configparser as cp
ImportError: No module named configparser
```

I did follow the instruction though

**Comment by earwig** [comment]
Seems like the latest version of GitPython no longer supports Python 2.7. You can try either upgrading to Python 3 (recommended) or installing GitPython < 3.0.0.

**Comment by jeffbabuyo** [comment]
@earwig I'm quite reluctant updating python manually it might mess up ubuntu, I tried it before and it ended up very bad

**Comment by earwig** [comment]
In that case, you need to downgrade GitPython, because the version you have is too new and is incompatible with the older Python.

**Comment by JedMeister** [comment]
@jeffbabuyo 

You state "new workstation" then "Ubuntu", so I assume you are using a relatively new version of Ubuntu.

FWIW on most Linux distros (there are some exceptions, such as Arch) `python` commands (including `pip`) default to use python2.7 (as you can see in the paths noted in your stacktrace). To use `python3` (including `pip`) you need to state it explicitly.

To install python3 version of pip (if you don't already have it):
```
sudo apt install python3-pip
```
Then to use the python3 version of `pip` to Install git-repo-updater for python3 
```
pip3 install gitup
```

**Comment by jeffbabuyo** [comment]
@earwig @JedMeister - all good now yeah I have to upgrade my ubuntu18.04 python version pip and its working now...I didn’t use gitpytjon though...closing this issue now
