### ISSUE TITLE
Incompatible with PyOxidizer 

### ISSUE THREAD

**Issue by Baneeishaque** [earwig/git-repo-updater#58]
See [PyOxidizer Issue 69 : Stop requiring `__file__` in Python packages](https://github.com/indygreg/PyOxidizer/issues/69)

I am trying to use [git-repo-updater](https://github.com/earwig/git-repo-updater) with PyOxidizer.
```
    Finished dev [unoptimized + debuginfo] target(s) in 1m 29s
writing executable to C:\Lab\PyOxidizer\git-repo-updator\.\build\x86_64-pc-windows-msvc\debug\exe\git-repo-updator.exe
>>> from gitup.cli import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gitup.cli", line 18, in <module>
  File "gitup.update", line 15, in <module>
  File "git", line 33, in <module>
  File "git", line 22, in _init_externals
NameError: name '__file__' is not defined
>>>
```
git-repo-updater uses GitPython package : [git-repo-updater setup.py](https://github.com/earwig/git-repo-updater/blob/develop/setup.py), [git-repo-updater source file](https://github.com/earwig/git-repo-updater/blob/develop/gitup/update.py)

**Comment by earwig** [comment]
This is not a problem with git-repo-updater, but with [GitPython](https://github.com/gitpython-developers/GitPython); please report the issue there.

**Comment by Baneeishaque** [comment]
Done

**Comment by earwig** [comment]
I think this should be fixed now as of GitPython 3.1.1?
