### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by scottjl** [earwig/git-repo-updater#8]
getting this error on some of the repos i try to update. :-(

vim-airline:
    Fetching origin (Traceback (most recent call last):
      File "/usr/local/bin/gitup", line 9, in <module>
    load_entry_point('gitup==0.2.2', 'console_scripts', 'gitup')()
      File "build/bdist.linux-x86_64/egg/gitup/script.py", line 90, in run
      File "build/bdist.linux-x86_64/egg/gitup/script.py", line 82, in main
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 288, in update_directories
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 267, in _update_directory
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 248, in _update_subdirectories
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 231, in _update_repository
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 90, in _fetch_remotes
      File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.6-py2.7.egg/git/remote.py", line 626, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
      File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.6-py2.7.egg/git/remote.py", line 541, in _get_fetch_info_from_stderr
    for pline in progress_handler(line):
      File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.6-py2.7.egg/git/util.py", line 285, in handler
    return self._parse_progress_line(line.rstrip())
      File "/usr/local/lib/python2.7/dist-packages/GitPython-0.3.6-py2.7.egg/git/util.py", line 275, in _parse_progress_line
    message)
      File "build/bdist.linux-x86_64/egg/gitup/update.py", line 44, in update
    TypeError: object of type 'float' has no len()

**Comment by earwig** [comment]
No idea what's going on here; the docs for GitPython don't ever mention giving a float for that value. I'll look into it more carefully.

**Comment by scottjl** [comment]
Ok. I don't know any more to help, but if there's anything else you need
from me just let me know. If I do a manual git pull on the directory it
comes down fine. Thanks!

**Comment by earwig** [comment]
Alright, I understand it now. Looks like a recent update to GitPython changed the way that API worked. Fix incoming.

**Comment by earwig** [comment]
Fixed in [v0.2.3](https://github.com/earwig/git-repo-updater/compare/v0.2.2...v0.2.3).
